### PR TITLE
Chapter 46 proofreading edits

### PR DESCRIPTION
**Pull request by tsanth**
This PR covers these things:
- Remove trailing whitespace
- Uniformly capitalize callsigns
- A single capitalization nit: a colon introduces a clause, not a new sentence

### CODE REVIEW

**Comment by tsanth** [comment]
This PR alone shouldn't close it, but see issue #65.

**Comment by ctwelve** [comment]
Hello,

Please be aware that the whitespace immediately after datelines is, in fact, deliberate. It's how you tell Markdown to do a linebreak without starting a new paragraph; basically it's an old-school `<br>`

**Review by ctwelve — APPROVED** [review]
Other than the minor linebreak issue (which I already committed a fix for) I am okay with this.

**Comment by tsanth** [comment]
Thanks for the info; I'll keep it in mind for future PRs.

**Pull request merged**
