### PR TITLE
Port "Good Training: Survival" from Web Archive.

### PR DESCRIPTION
**Pull request by SwiftyPants**
Pull the text from https://web.archive.org/web/20180104103022/http://hfy-archive.org/book/good-training/survival
and clipped non-content HTML. Ran the result through an HTML-to-Markdown converter.

Visually inspected the markdown text in Vim for issues.

Committing to Github to read the text in their renderer.

### CODE REVIEW

**Comment by SwiftyPants** [comment]
Since there's no install for the site, and it's pure markdown, I have no way to verify everything will be detected correctly.

I was disappointed to find only the first section in the reddit post, but delighted to find the archive. Figured I'd do the heavy lifting to try and get the content on the new site.

**Comment by ctwelve** [comment]
Hello!

Sorry for the long delay, I am finally in possession of a computer and will review now!

**Review by ctwelve — DISMISSED** [review]
Damn! It's about perfect right off the bat!

**Review by ctwelve — APPROVED** [review]
There! All issues fixed. Thank you so much!

**Pull request merged**
